Blog/blogs/urls.py
"""Defines patterns for blogposts"""

from django.urls import path
from . import views

app_name = 'blogs'

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    path('new_blogpost/', views.new_blogpost, name='new_blogpost'),
    path('edit_blogpost/<int:blogpost_id>', views.edit_blogpost, name='edit_blogpost')
]

Blog/blogs/models.py
from django.db import models


class BlogPost(models.Model):
    """Пост, который может добавить пользователь"""
    title = models.CharField(max_length=50)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """returns a string representation of the model"""
        return self.title

Blog/blogs/forms.py
from django import forms
from .models import BlogPost

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        labels = {'title': '', 'text': ''}

Blog/blogs/views.py
from django.shortcuts import render, redirect
from .models import BlogPost
from .forms import BlogPostForm


def index(request):
    """Домашняя страница, на которой выводятся все посты"""
    blogposts = BlogPost.objects.order_by("-date_added")

    context = {'blogposts': blogposts}
    return render(request, 'blogs/index.html', context)


def new_blogpost(request):
    """Определяет новый блогпост"""
    if request.method != 'POST':
        # Данные не отправлялись, создается пустая форма
        form = BlogPostForm()
    else:
        # Отправленны данные POST; обработать данные.
        form = BlogPostForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    # Вывести пустую или недействительную форму
    context = {'form': form}
    return render(request, 'blogs/new_blogpost.html', context)


def edit_blogpost(request, blogpost_id):
    """Рекдактирует существующий пост"""
    blogpost=BlogPost.objects.get(id=blogpost_id)

    if request.method != 'POST':
        # Исходный запрос, форма заполняется данными текущего поста
        form = BlogPostForm(instance=blogpost)
    else:
        # Отправка данных POST, обработать данные
        form = BlogPostForm(instance=blogpost, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')

    context = {'blogpost': blogpost, 'form': form}
    return render(request, 'blogs/edit_blogpost.html', context)

Blog/blogs/templates/blogs/base.html
<p>
    <a href="{% url 'blogs:index' %}">Домашняя страница</a> -
    {% if user.is_authenticated %}
      Привет, {{ user.username }}
    {% else %}
      <a href="{% url 'accounts:register' %}">зарегистрироваться</a>
      <a href="{% url 'accounts:login' %}">войти</a>
    {% endif %}
</p>

{% block content %}{% endblock content %}

{% if user.is_authenticated %}
  <hr />
  <form action="{% url 'accounts:logout' %}" method="post">
    {% csrf_token %}
      <button name='submit'>выход</button>

  </form>
{% endif %}

Blog/blogs/templates/blogs/edit_blogpost.html
{% extends "blogs/base.html" %}

{% block content %}
  <p>Измените пост:</p>
  <form action="{% url 'blogs:edit_blogpost' blogpost.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">сохранить изменения</button>
  </form>

{% endblock content %}

Blog/blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block content %}
  <a href="{% url 'blogs:new_blogpost' %}">Добавить новый пост:</a>
  <p>Посты:</p>

  <ul>
    {% for blogpost in blogposts %}
      <li><a>{{ blogpost.title }}</a></li>
      <li>{{ blogpost.date_added }}</li>
      <li>{{ blogpost.text }}</li>
      <li>
        <a href="{% url 'blogs:edit_blogpost' blogpost.id %}">Изменить пост</a>
      </li>
    {% empty %}
      <li>Ни один пост еще не был добавлен.</li>
    {% endfor %}
  </ul>


{% endblock content %}

Blog/blogs/templates/blogs/new_blogpost.html
{% extends "blogs/base.html" %}

{% block content %}
  <p>Добавьте новый пост:</p>
  <form action="{% url 'blogs:new_blogpost' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">добавить пост</button>
  </form>

{% endblock content %}